python:
   version: 3.7
   install:
      - requirements: docs/requirements.txt
        method: pip

sphinx:
    builder: html
    configuration: docs/conf.py
    fail_on_warning: false

# Build PDF & ePub
formats:
  - htmlzip
