version: 2

jobs:
  test-client:
    machine: true
    steps:
      - checkout
      - run: make test-client
  test-contracts:
    machine: true
    steps:
      - checkout
      - run: make test-contracts
  test-hub:
    machine: true
    steps:
      - checkout
      - run: make test-hub
  test-e2e:
    machine: true
    steps:
      - checkout
      - run: make test-e2e
  push-images:
    machine: true
    steps:
      - checkout
      - run: make push
  push-live-images:
    machine: true
    steps:
      - checkout
      - run: make push-live
  deploy-staging:
    machine: true
    steps:
      - checkout
      - run: ssh dev@staging.bohendo.com bash -c "cd indra && git pull && bash ops/restart prod"
  deploy-live:
    machine: true
    steps:
      - checkout
      - run: ssh dev@staging.bohendo.com bash -c "cd indra && git pull && MODE=live bash ops/restart prod"

workflows:
  version: 2
  test:
    jobs:
      - test-client
      - test-contracts
      - test-hub
      - test-e2e
  deploy-staging:
    jobs:
      - test-client
      - test-contracts
      - test-hub
      - test-e2e
      - push-images
      - deploy-stagin:
          requires:
            - test-client
            - test-contracts
            - test-hub
            - test-e2e
            - push-images
  deploy-live:
    jobs:
      - test-client
      - test-contracts
      - test-hub
      - test-e2e
      - push-live-images
      - deploy-live:
          requires:
            - test-client
            - test-contracts
            - test-hub
            - test-e2e
            - push-live-images
          filters:
            branches:
              only: master

# keep the npm cache around to speed up installs
cache:
  directories:
  - "$HOME/modules/client/.npm"
  - "$HOME/modules/contracts/.npm"
  - "$HOME/modules/database/.npm"
  - "$HOME/modules/hub/.npm"
  - "$HOME/modules/wallet/.npm"
