version: 2.1

executors:
  executor:
    machine: true
    working_directory: /tmp/workspace

jobs:
  build:
    executor: executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-{{ .Branch }}
      - run: make prod
      - save_cache:
          key: node-modules-{{ .Branch }}
          paths:
            - "modules/client/.npm"
            - "modules/client/node_modules"
            - "modules/contracts/.npm"
            - "modules/contracts/node_modules"
            - "modules/database/.npm"
            - "modules/database/node_modules"
            - "modules/hub/.npm"
            - "modules/hub/node_modules"
            - "modules/wallet/.npm"
            - "modules/wallet/node_modules"
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - build
            - modules
            - node_modules

  test-client:
    executor: executor
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: make test-client

  test-contracts:
    executor: executor
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: make test-contracts

  test-hub:
    executor: executor
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: make test-hub

  test-e2e:
    executor: executor
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: make test-e2e

  push-images:
    executor: executor
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: make push

  push-live-images:
    executor: executor
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: make push-live

  deploy-staging:
    executor: executor
    steps:
      - run: |
          ssh dev@staging.bohendo.com bash -c '
            rm -rf indra
            git clone https://github.com/ConnextProject/indra.git
            cd indra
            bash ops/restart prod
          '

  deploy-live:
    executor: executor
    steps:
      - run: |
          ssh dev@staging.bohendo.com bash -c '
            rm -rf indra
            git clone https://github.com/ConnextProject/indra.git
            cd indra
            MODE=live bash ops/restart prod
          '

workflows:
  version: 2.1

  test-and-deploy:
    jobs:
      - build
      - test-client:
          requires:
            - build
      - test-contracts:
          requires:
            - build
      - test-hub:
          requires:
            - build
      - test-e2e:
          requires:
            - build
      - push-images:
          requires:
            - test-client
            - test-contracts
            - test-hub
            - test-e2e
      - push-live-images:
          filters:
            branches:
              only: master
          requires:
            - test-client
            - test-contracts
            - test-hub
            - test-e2e
      - deploy-staging:
          filters:
            branches:
              ignore: master
          requires:
            - push-images
      - deploy-live:
          filters:
            branches:
              only: master
          requires:
            - push-live-images

# keep the npm cache around to speed up installs
cache:
  directories:
