version: 2
jobs:
  test:
    machine: true
    steps:
      - checkout
      - run: make test
  deploy:
    machine: true
    steps:
      - checkout
      - run: make deploy
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
