version: 2.1

executors:
  executor:
    machine: true
    working_directory: /tmp

jobs:
  build:
    executor: executor
    steps:
      - checkout
      - run: make prod
      - persist_to_workspace:
          root: /tmp
          paths:
            - build
            - modules
            - node_modules

  test-client:
    executor: executor
    steps:
      - attach_workspace:
          at: /tmp
      - run: make test-client

  test-contracts:
    executor: executor
    steps:
      - attach_workspace:
          at: /tmp
      - run: make test-contracts

  test-hub:
    executor: executor
    steps:
      - attach_workspace:
          at: /tmp
      - run: make test-hub

  test-e2e:
    executor: executor
    steps:
      - attach_workspace:
          at: /tmp
      - run: make test-e2e

  push-images:
    executor: executor
    steps:
      - attach_workspace:
          at: /tmp
      - run: make push

  push-live-images:
    executor: executor
    steps:
      - attach_workspace:
          at: /tmp
      - run: make push-live

  deploy-staging:
    executor: executor
    steps:
      - attach_workspace:
          at: /tmp
      - run: ssh dev@staging.bohendo.com bash -c "cd indra && git pull && bash ops/restart prod"

  deploy-live:
    executor: executor
    steps:
      - attach_workspace:
          at: /tmp
      - run: ssh dev@staging.bohendo.com bash -c "cd indra && git pull && MODE=live bash ops/restart prod"

workflows:
  version: 2.1

  test-and-deploy:
    jobs:
      - build
      - test-client:
          requires:
            - build
      - test-contracts:
          requires:
            - build
      - test-hub:
          requires:
            - build
      - test-e2e:
          requires:
            - build
      - push-images:
          requires:
            - test-client
            - test-contracts
            - test-hub
            - test-e2e
      - push-live-images:
          filters:
            branches:
              only: master
          requires:
            - test-client
            - test-contracts
            - test-hub
            - test-e2e
      - deploy-staging:
          filters:
            branches:
              ignore: master
          requires:
            - push-images
      - deploy-live:
          filters:
            branches:
              only: master
          requires:
            - push-live-images

# keep the npm cache around to speed up installs
cache:
  directories:
  - "$HOME/modules/client/.npm"
  - "$HOME/modules/contracts/.npm"
  - "$HOME/modules/database/.npm"
  - "$HOME/modules/hub/.npm"
  - "$HOME/modules/wallet/.npm"
