version: 2
jobs:
  test:
    steps:
      - checkout circle-ci
      - run: make test
  deploy:
    steps:
      - checkout circle-ci
      - run: make deploy
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
