name: CD Tests

on:
  push:
    branches-ignore:
      - master
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: make node-modules
    - run: make all

  test-node:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: make dev
    - run: make build-report
    - run: make test-node

  test-cf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: make dev
    - run: make build-report
    - run: make test-cf

  test-bot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: make prod
    - run: make build-report
    - run: make start-test
    - run: make test-bot

  test-bot-farm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: make prod
    - run: make build-report
    - run: make start-test
    - run: make test-bot-farm

  test-daicard:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: make prod
    - run: make build-report
    - run: make start-test
    - run: make test-daicard

  test-ssh:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: ssh test
      uses: ./ops/ssh-action/
      with:
        HOST: ubuntu@staging.indra.connext.network:22
        SSH_KEY: ${{ secrets.SSH_KEY }}
        CMD: '
          echo "we are in";
          hostname;
        '
