name: CD

on:
  push:
    branches:
      - master
      - staging

jobs:
  full-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: make clean
    - run: make reset
    - run: make prod
    - run: make test-node
    - run: make test-cf
    - run: make start-test
    - run: make test-bot
    - run: make test-ui
    - run: make stop
