name: CD

on:
  push:
    branches:
      - master
      - staging

jobs:
  test-units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: make dev
    - run: make test-cf
    - run: make test-node

  test-bot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: make prod
    - run: make start-test
    - run: make test-bot

  test-ui:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: make prod
    - run: make start-test
    - run: make test-ui

  push-latest:
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    if: endsWith(github.ref, 'staging')
    needs: [test-units, test-bot, test-ui]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: push images
      run: make push-latest

  push-versioned:
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    if: endsWith(github.ref, 'master')
    needs: [test-units, test-bot, test-ui]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: push images
      run: make push-versioned
