name: CI Tests

on:
  push:
    branches-ignore:
      - master
      - staging

jobs:
  test-cf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: .npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-
    - run: make cf-core
    - run: make test-cf

  test-watcher:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: .npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-
    - run: make watcher
    - run: make test-watcher

  test-node:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: make node
    - run: make test-node

  test-contracts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: .npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-
    - run: make contracts
    - run: make test-contracts

  test-utils:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: .npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-
    - run: make utils
    - run: make test-utils

  test-integration:
    env:
      INDRA_ADMIN_TOKEN: ${{ secrets.INDRA_ADMIN_TOKEN }}
      INDRA_NATS_JWT_SIGNER_PRIVKEY: ${{ secrets.INDRA_NATS_JWT_SIGNER_PRIVKEY }}
      INDRA_NATS_JWT_SIGNER_PUBKEY: ${{ secrets.INDRA_NATS_JWT_SIGNER_PUBKEY }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: .npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-
    - run: make pull-latest
    - run: make
    - run: make start-headless
    - run: make build-report
    - run: sleep 15 && make dls
    - run: make test-integration
    - name: Print logs
      if: failure()
      run: docker service logs --tail 200 indra_node && docker service logs --tail 200 indra_proxy
