name: CI Tests

on:
  push:
    branches-ignore:
      - master
      - staging

jobs:
  test-cf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: .npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-
    - run: make cf-core
    - run: make test-cf

  test-bot-self:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - run: make clean && make reset
    - run: make node-modules
    - run: make start-headless
    - run: make build-report
    - run: make test-bot

  test-bot-github:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: .npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-
    - run: make node-modules
    - run: make start-headless
    - run: make build-report
    - run: make test-bot

  test-bot-github-nocache:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: make node-modules
    - run: make start-headless
    - run: make build-report
    - run: make test-bot
