name: CI Tests

on:
  push:
    branches-ignore:
      - master
      - staging

jobs:
  test-cf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: make dev
    - run: make build-report
    - run: make test-cf

  test-bot:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - run: make clean && make reset
    - run: make start-headless
    - run: make build-report
    - run: make test-bot
    - run: make stop
