name: CI

on:
  push:
    branches-ignore:
      - master
      - staging

jobs:
  test-bot:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - run: make dev
    - run: make start-headless
    - run: make test-bot
