name: CI

on:
  push:
    branches-ignore:
      - master
      - staging

jobs:
  quick-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: make clean && make reset
    - run: make start-headless
    - run: make build-report
    - run: make test-bot
    - run: make stop
