name: CI

on:
  push:
    branches-ignore:
      - master
      - staging

jobs:
  quick-test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - run: make clean
    - run: make reset
    - run: make dev
    - run: make start-headless
    - run: make test-bot
    - run: make stop
