name: CI

on:
  push:
    branches-ignore:
      - master
      - staging

jobs:
  test-bot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: make prod
    - run: make start-test
    - run: make test-bot
